name: uptodo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
#  slide: ^2.3.0
#  path_provider: ^2.1.1
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  get: ^4.7.2
  intl: ^0.20.2
  fl_chart: ^0.71.0
  flutter_svg: ^2.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter-icons:
  android: true
  image_path: "assets/images/checklist.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
